<?php
$posts = $block->getCollection();
?>
<?php if($block->getData('posts')): ?>
	<div class="row">
        <?php foreach ($posts as $post) : ?>
            <div class="post-list-item">
                <div class="post-item-wraper">
                    <?php if ($post->getImage()) : ?>
                        <div class="post-image">
                            <a href="<?= $post->getUrl() ?>">
                                <img class="img-responsive" style="height: 220px"
                                     src="<?= $block->resizeImage($post->getImage(), '400x'); ?>"
                                     alt="<?= $block->escapeHtml($post->getName()); ?>"/>
                            </a>
                        </div>
                    <?php endif; ?>
                    <div class="post-info-wraper">
                        <h2 class="mp-post-title" style="font-size: 22px">
                            <a class="post-link-title" title="<?= $post->getName(); ?>"
                               href="<?= $post->getUrl() ?>">
                                <?= $post->getName(); ?>
                            </a>
                        </h2>
                        <div class="mp-post-info">
                            <?= $block->getPostInfo($post) ?>
                        </div>
                        <div class="post-short-description">
                            <p><?= $post->getShortDescription(); ?></p>
                        </div>
                        <div class="mp-clearfix"></div>
                        <div class="mp-post-meta-info mp-alignright">
                            <div class="actions">
                                <a class="mp-read-more" href="<?= $post->getUrl(); ?>"
                                   title="<?= __('Read More'); ?>"><?= __('Read more'); ?></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

?>
